export const companies = [
  {
    id: 91,
    nombre: "Grupo Carrasco Holding SA de CV",
    rfc: "ANDNN324NS",
    moneda: "MXN",
    contacts: [
      {
        id: 1,
        name: 'Raul Gallego León',
        type: 'Banquero privado',
        categoryCoreId: 50,
        coreId: 34,
        number: '6691481888',
        location: 'Mazatlán, Sinaloa',
        email: 'raul@gallegosbanca.com'
      },
    ],
    containedIntrusts:[],
    actaConstitutiva: "https://www.google.drive/1423nger",
    actasAsamblea: [
      {
        name: "AAO 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actaAsambleaExtraordinaria: [],
    poderes: [
      {
        name: "Poderes 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    razonSocial: "Grupo Carrasco Holding SA de CV",
    valuacion: "123,000,000.00",
    direccionFiscal: "Col La Primaver parque industrial CP 233",
    fundacion: "10/10/1995",
    percentage: "100",
    nationality: "Mexicana",
    regimenCapital: "SA de CV",
    bankAccounts: [
      {
        id: 2,
        bank: "BBVA",
        accountNumber: "34333311021",
      },
    ],
    owners: [
      {
        type: "family",
        pct: "100",
        coreId: "23",
        name: "Francisco Carrasco Ramos",
        capitalSocial: "1500000",
      },
    ],
    actasDividendos: [
      {
        name: "AD 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Actas dividendos 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    cif: "",
    reports: {
      mensuales: [
        {
          year: "2024",
          accounting: [
            {
              id: 1,
              year: "2024",
              month: "Enero",
              utilidad: "495000.00",
              ventas: "1430000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 2,
              year: "2024",
              month: "Febrero",
              utilidad: "385000.00",
              ventas: "925000.00",
              egresos: "180000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Marzo",
              utilidad: "116000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Abril",
              utilidad: "106000.00",
              ventas: "825000.00",
              egresos: "210000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Mayo",
              utilidad: "196000.00",
              ventas: "1025000.00",
              egresos: "180000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Junio",
              utilidad: "316000.00",
              ventas: "1225000.00",
              egresos: "1453000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Julio",
              utilidad: "102000.00",
              ventas: "625000.00",
              egresos: "480000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Agosto",
              utilidad: "216000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Septiembre",
              utilidad: "92000.00",
              ventas: "320000.00",
              egresos: "180000.00",
              isr: "",
              iva: "",
              diot: "",
            },
          ],
        },
        {
          year: "2023",
          accounting: [
            {
              id: 4,
              month: "Octubre",
              year: "2023",
              utilidad: "495000.00",
              ventas: "1430000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 5,
              year: "2023",
              month: "Noviembre",
              utilidad: "275000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 6,
              month: "Diciembre",
              year: "2023",
              utilidad: "275000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "",
              iva: "",
              diot: "https://www.google.drive/1423nge",
            },
          ],
        },
      ],
      anuales: [
        {
          id: 94,
          year: "2022",
          utilidad: "2375000.00",
          ventas: "9245000.00",
          egresos: "2840000.00",
          isr: "https://www.google.drive/1423nger",
          iva: "https://www.google.drive/1423nger",
          diot: "https://www.google.drive/1423nger",
        },
        {
          id: 97,
          year: "2023",
          utilidad: "1975000.00",
          ventas: "1925000.00",
          egresos: "1280000.00",
          isr: "https://www.google.drive/1423nger",
          iva: "https://www.google.drive/1423nger",
          diot: "https://www.google.drive/1423nger",
        },
      ],
    },
  },
  {
    id: 85,
    nombre: "CN Market Transportation LLC",
    rfc: "JNF932NKEW",
    moneda: "USD",
    containedIntrusts:[],
    contacts: [
      {
        id: 1,
        name: 'Raul Gallego León',
        type: 'Banquero privado',
        categoryCoreId: 50,
        coreId: 34,
        number: '6691481888',
        location: 'Mazatlán, Sinaloa',
        email: 'raul@gallegosbanca.com'
      },
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    actasAsamblea: [
      {
        name: "AAO 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actaAsambleaExtraordinaria: [
      {
        name: "AAE 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    poderes: [
      {
        name: "Poderes 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actasDividendos: [
      {
        name: "AD 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Actas dividendos 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    razonSocial: "CN Market Transportation LLC",
    valuacion: "200,000.00",
    direccionFiscal: "Col Los pinos 233 Colonia Mutualismo CP 233",
    fundacion: "10/10/1995",
    nationality: "USA",
    regimenCapital: "SA de CV",
    bankAccounts: [],
    capitalSocial: "2,300,000.00",
    owners: [
      {
        type: "trust",
        pct: "100",
        coreId: 20,
        name: "0014233 Santander",
        capitalSocial: "2000000",
      },
    ],
    percentage: "100",
    cif: "",
    reports: {
      mensuales: [
        {
          year: "2024",
          accounting: [
            {
              id: 995,
              month: "Enero",
              year: "2024",
              utilidad: "425000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 322,
              month: "Febrero",
              year: "2024",
              utilidad: "325000.00",
              ventas: "525000.00",
              egresos: "380000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 991,
              month: "Marzo",
              year: "2024",
              utilidad: "485000.00",
              ventas: "995000.00",
              egresos: "210000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 995,
              month: "Mayo",
              year: "2024",
              utilidad: "825000.00",
              ventas: "1205000.00",
              egresos: "580000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 995,
              month: "Junio",
              year: "2024",
              utilidad: "125000.00",
              ventas: "325000.00",
              egresos: "480000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 995,
              month: "Julio",
              year: "2024",
              utilidad: "635000.00",
              ventas: "1125000.00",
              egresos: "520000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 995,
              month: "Agosto",
              year: "2024",
              utilidad: "425000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
          ],
        },
      ],
      anuales: [],
    },
  },
  {
    id: 23,
    nombre: "Agricola Carrasco SA de CV",
    rfc: "BVA4930245",
    moneda: "MXN",
    contacts: [
      {
        id: 1,
        name: 'Raul Gallego León',
        type: 'Banquero privado',
        categoryCoreId: 50,
        coreId: 34,
        number: '6691481888',
        location: 'Mazatlán, Sinaloa',
        email: 'raul@gallegosbanca.com'
      },
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    containedIntrusts:[
      {
        id: 90, 
        name: '144002-BBVA'
      }
    ],
    actaConstitutiva: "https://www.google.drive/1423nger",
    actasAsamblea: [
      {
        name: "AAO 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actaAsambleaExtraordinaria: [],
    poderes: [
      {
        name: "Poderes 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    razonSocial: "Agricola Carrasco SA de CV",
    valuacion: "31,000,000.00",
    direccionFiscal: "Col Los pinos 233 Colonia Mutualismo CP 233",
    fundacion: "10/10/1995",
    percentage: "100",
    nationality: "Mexicana",
    regimenCapital: "SA de CV",
    bankAccounts: [
      {
        id: 2,
        bank: "BBVA",
        accountNumber: "34333311021",
      },
    ],
    owners: [
      {
        type: "company",
        pct: "40",
        coreId: "91",
        name: "Grupo Carrasco Holding SA de CV",
        capitalSocial: "1000000",
      },
      {
        type: "family",
        pct: "60",
        coreId: "23",
        name: "Francisco Carrasco Ramos",
        capitalSocial: "1500000",
      },
    ],
    actasDividendos: [
      {
        name: "AD 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Actas dividendos 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    cif: "",
    reports: {
      mensuales: [
        {
          year: "2024",
          accounting: [
            {
              id: 1,
              year: "2024",
              month: "Enero",
              utilidad: "495000.00",
              ventas: "1430000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 2,
              year: "2024",
              month: "Febrero",
              utilidad: "385000.00",
              ventas: "925000.00",
              egresos: "180000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "",
              diot: "",
            },
            {
              id: 3,
              year: "2024",
              month: "Marzo",
              utilidad: "116000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 4,
              year: "2024",
              month: "Abril",
              utilidad: "266000.00",
              ventas: "725000.00",
              egresos: "240000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 5,
              year: "2024",
              month: "Mayo",
              utilidad: "816000.00",
              ventas: "1025000.00",
              egresos: "480000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 6,
              year: "2024",
              month: "Junio",
              utilidad: "96000.00",
              ventas: "825000.00",
              egresos: "180000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 7,
              year: "2024",
              month: "Julio",
              utilidad: "916000.00",
              ventas: "1225000.00",
              egresos: "380000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 8,
              year: "2024",
              month: "Agosto",
              utilidad: "116000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "",
              iva: "",
              diot: "",
            },
          ],
        },
        {
          year: "2023",
          accounting: [
            {
              id: 4,
              month: "Octubre",
              year: "2023",
              utilidad: "495000.00",
              ventas: "1430000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 5,
              year: "2023",
              month: "Noviembre",
              utilidad: "275000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 6,
              month: "Diciembre",
              year: "2023",
              utilidad: "175000.00",
              ventas: "625000.00",
              egresos: "380000.00",
              isr: "",
              iva: "",
              diot: "https://www.google.drive/1423nge",
            },
          ],
        },
      ],
      anuales: [
        {
          id: 94,
          year: "2023",
          utilidad: "2375000.00",
          ventas: "9245000.00",
          egresos: "2840000.00",
          isr: "https://www.google.drive/1423nger",
          iva: "https://www.google.drive/1423nger",
          diot: "https://www.google.drive/1423nger",
        },
      ],
    },
  },
  {
    id: 24,
    nombre: "Servicios financieros del campo CN SA de CV",
    rfc: "BVA4930245",
    moneda: "MXN",
    containedIntrusts:[],
    razonSocial: "Servicios financieros del campo CN SA de CV",
    nationality: "Mexicana",
    regimenCapital: "SA de CV",
    bankAccounts: [],
    contacts: [
      {
        id: 1,
        name: 'Raul Gallego León',
        type: 'Banquero privado',
        categoryCoreId: 50,
        coreId: 34,
        number: '6691481888',
        location: 'Mazatlán, Sinaloa',
        email: 'raul@gallegosbanca.com'
      },
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    capitalSocial: "2,300,000.00",
    owners: [
      {
        type: "family",
        pct: "30",
        coreId: "12",
        name: "Javier Carrasco Nieto",
        capitalSocial: "1000000",
      },
      {
        type: "family",
        pct: "30",
        coreId: "23",
        name: "Francisco Carrasco Ramos",
        capitalSocial: "1500000",
      },
      {
        type: "company",
        pct: "40",
        coreId: "91",
        name: "Grupo Carrasco Holding SA de CV",
        capitalSocial: "15000",
      },
    ],
    valuacion: "10,000,000.00",
    fundacion: "10/10/2005",
    percentage: "100",
    direccionFiscal: "Col Los pinos 233 Colonia Mutualismo CP 233",
    actaConstitutiva: "https://www.google.drive/1423nger",
    actasAsamblea: [
      {
        name: "AAO 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actaAsambleaExtraordinaria: [
      {
        name: "AAE 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    poderes: [
      {
        name: "Poderes 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actasDividendos: [
      {
        name: "AD 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Actas dividendos 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    cif: "",
    reports: {
      mensuales: [
        {
          year: "2024",
          accounting: [
            {
              id: 7,
              month: "Enero",
              year: "2024",
              utilidad: "425000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 8,
              year: "2024",
              month: "Febrero",
              ventas: "1325000.00",
              egresos: "480000.00",
              utilidad: "275000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "",
              diot: "",
            },
            {
              id: 9,
              year: "2024",
              month: "Marzo",
              ventas: "325000.00",
              egresos: "380000.00",
              utilidad: "-23292.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 10,
              year: "2024",
              month: "Abril",
              ventas: "925000.00",
              egresos: "280000.00",
              utilidad: "516000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 11,
              year: "2024",
              month: "Mayo",
              ventas: "425000.00",
              egresos: "180000.00",
              utilidad: "216000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 12,
              year: "2024",
              month: "Junio",
              ventas: "1225000.00",
              egresos: "580000.00",
              utilidad: "316000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 13,
              year: "2024",
              month: "Julio",
              ventas: "425000.00",
              egresos: "380000.00",
              utilidad: "16000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 14,
              year: "2024",
              month: "Agosto",
              ventas: "925000.00",
              egresos: "280000.00",
              utilidad: "516000.00",
              isr: "",
              iva: "",
              diot: "",
            },
          ],
        },
      ],
      anuales: [],
    },
  },
  
  {
    id: 53,
    nombre: "CN Farmer trade LLC",
    rfc: "NJF9NIEW2",
    moneda: "USD",
    containedIntrusts:[],
    contacts: [
      {
        id: 1,
        name: 'Raul Gallego León',
        type: 'Banquero privado',
        categoryCoreId: 50,
        coreId: 34,
        number: '6691481888',
        location: 'Mazatlán, Sinaloa',
        email: 'raul@gallegosbanca.com'
      },
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    actasAsamblea: [
      {
        name: "AAO 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actaAsambleaExtraordinaria: [
      {
        name: "AAE 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "AAE 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    poderes: [
      {
        name: "Poderes 2022",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Poderes 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    actasDividendos: [
      {
        name: "AD 2023",
        url: '"https://www.google.drive/1423nger"',
      },
      {
        name: "Actas dividendos 2024",
        url: '"https://www.google.drive/1423nger"',
      },
    ],
    razonSocial: "CN Farmer trade LLC",
    valuacion: "1,200,000.00",
    direccionFiscal: "901 BRUSH ST APT 323 LAS VEGAS NV 89107-4058 USA",
    fundacion: "10/10/2022",
    nationality: "USA",
    regimenCapital: "LLC",
    bankAccounts: [],
    capitalSocial: "200,000.00",
    owners: [
      {
        type: "family",
        pct: "20",
        coreId: "12",
        name: "Javier Carrasco Nieto",
        capitalSocial: "1000000",
      },
      {
        type: "family",
        pct: "20",
        coreId: "23",
        name: "Francisco Carrasco Ramos",
        capitalSocial: "1500000",
      },
      {
        type: "company",
        pct: "40",
        coreId: "91",
        name: "Grupo Carrasco Holding SA de CV",
        capitalSocial: "15000",
      },
      {
        type: "family",
        coreId: '13',
        pct: "20",
        name: 'Adriana Carrasco Nieto',
        capitalSocial: "5000",
      }
    ],
    percentage: "100",
    cif: "",
    reports: {
      mensuales: [
        {
          year: "2024",
          accounting: [
            {
              id: 7,
              month: "Enero",
              year: "2024",
              utilidad: "425000.00",
              ventas: "925000.00",
              egresos: "280000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "https://www.google.drive/1423nger",
              diot: "https://www.google.drive/1423nger",
            },
            {
              id: 8,
              year: "2024",
              month: "Febrero",
              ventas: "1325000.00",
              egresos: "480000.00",
              utilidad: "275000.00",
              isr: "https://www.google.drive/1423nger",
              iva: "",
              diot: "",
            },
            {
              id: 9,
              year: "2024",
              month: "Marzo",
              ventas: "825000.00",
              egresos: "680000.00",
              utilidad: "23292.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 10,
              year: "2024",
              month: "Abril",
              ventas: "825000.00",
              egresos: "620000.00",
              utilidad: "246000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 11,
              year: "2024",
              month: "Mayo",
              ventas: "1425000.00",
              egresos: "1180000.00",
              utilidad: "1216000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 12,
              year: "2024",
              month: "Junio",
              ventas: "1225000.00",
              egresos: "580000.00",
              utilidad: "316000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 13,
              year: "2024",
              month: "Julio",
              ventas: "425000.00",
              egresos: "380000.00",
              utilidad: "16000.00",
              isr: "",
              iva: "",
              diot: "",
            },
            {
              id: 14,
              year: "2024",
              month: "Agosto",
              ventas: "625000.00",
              egresos: "380000.00",
              utilidad: "316000.00",
              isr: "",
              iva: "",
              diot: "",
            },
          ],
        },
      ],
      anuales: [],
    },
  },
];

export const fideicomisos = [
  {
    id: 20,
    trustCreation: "10/10/2018",
    contract: "https://www.google.drive/1423nger",
    trustNumber: "0014233",
    trustType: "Patrimonial revocable with right of reversion",
    trusteeBank: "Santander",
    contacts: [
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    trustors: [
      {
        type: "family",
        id: "12",
        name: "Javier Carrasco Nieto",
      },
      {
        type: "family",
        id: "13",
        name: "Javier Carrasco Nieto",
      },
      {
        type: "family",
        id: "9",
        name: "Sofia Carrasco Nieto",
      },
    ],
    trustee: 'Carlos Carrasco Ramos',
    purpose: "Manejar las inversiones familiares a largo plazo",
    content: [
      {
        id: 15,
        coreId: 1,
        type: 'vehicle', 
        name: "Audi - A3",
        pct: 30,
        currency: 'MXN',
        country: 'México', 
        value: "600000",
      },
      {
        id: 32,
        coreId: 43,
        type: 'artAndOthers', 
        pct: 65,
        currency: 'EUR',
        country: 'España', 
        name: "Coleccion de arte de Gerhard Richter",
        value: "2,000,000.00",
      },
      {
        id: 44,
        coreId: 2,
        type: 'privateEquity', 
        country: 'México', 
        name: "Fondo ABC-Venture Capital",
        currency: 'MXN',
        pct: 100,
        value: "2,000,000.00",
      },
      {
        id: 25,
        coreId: 85,
        name: 'CN Market Transportation LLC',
        type: 'company',
        pct: '100',
        value: '200,000.00',
        currency: 'USD',
        country: 'USA'
      },
      {
        id: 4,
        coreId: 1,
        type: 'bankAccount', 
        pct: 100,
        country: 'México', 
        name: "Santander-100434346583",
        currency: 'MXN',
        value: "2,000,000.00",
      },
    ],
    country: "México",
  },
  {
    id: 90,
    contract: "https://www.google.drive/1423nger",
    trustNumber: "144002",
    trustCreation: "10/10/2018",
    trustType: "Testamentario",
    trusteeBank: "BBVA",
    contacts: [
      {
        id: 1,
        name: 'Juan Diaz Zalazar',
        type: 'Notario',
        categoryCoreId: 24,
        coreId: 17,
        number: '6671481888',
        location: 'Culiacan, Sinaloa',
        email: 'jaundiaz@zalazar.com'
      }
    ],
    trustors: [
      {
        type: "family",
        id: '12',
        type: 'artAndOthers', 
        name: "Javier Carrasco Nieto",
      },
      {
        type: "family",
        id: '13',
        name: "Javier Carrasco Nieto",
      },
      {
        type: "family",
        id: '9',
        name: "Sofia Carrasco Nieto",
      },
    ],
    trustee: 'Francisco Carrasco Ramos',
    purpose: "Dar claridad a la suceción del testamento de la Familia Aldana Ríos",
    content: [
      {
        id: 99,
        coreId: 23,
        name: 'Nissan Frontier',
        type: 'vehicle',
        pct: '100',
        value: '650,000.00',
        currency: 'MXN',
        country: 'México'
      },
      {
        id: 53,
        coreId: 499,
        name: 'Scotia Bank - 6641232',
        type: 'stockInvestment',
        pct: '50',
        value: '2,000,000.00',
        currency: 'MXN',
        country: 'México'
      },
    ],
    country: "México",
  },
];
