export const companies = [
  {
    id: 23,
    nombre: "Aldana Clima Integral SA de CV",
    rfc: "BVA4930245",
    moneda: 'MXN',
    actaConstitutiva: 'https://www.google.drive/1423nger', 
    actaAsamblea: 'https://www.google.drive/1423nger', 
    actaAsambleaExtraordinaria: 'https://www.google.drive/1423nger', 
    poderes: 'https://www.google.drive/jgierei2322',
    actasDividendos: '',
    cif: '',
    // reports: {
    //   mensuales: [], 
    //   anuales: []
    // }
    reports: [
      {
        year: "2025",
        accounting: [
          {
            id: 1,
            year: "2025",
            month: "Enero",
            utilidad: "495000.00",
            ventas: "1430000.00",
            egresos: "280000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "https://www.google.drive/1423nger",
            diot: "https://www.google.drive/1423nger",
          },
          {
            id: 2,
            year: "2025",
            month: "Febrero",
            utilidad: "385000.00",
            ventas: "925000.00",
            egresos: "180000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "",
            diot: "",
          },
          {
            id: 3,
            year: "2025",
            month: "Marzo",
            utilidad: "116000.00",
            ventas: "925000.00",
            egresos: "280000.00",
            isr: "",
            iva: "",
            diot: "",
          },
        ],
      },
      {
        year: "2023",
        accounting: [
          {
            id: 4,
            month: "Enero",
            year: "2023",
            utilidad: "495000.00",
            ventas: "1430000.00",
            egresos: "280000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "https://www.google.drive/1423nger",
            diot: "https://www.google.drive/1423nger",
          },
          {
            id: 5,
            year: "2023",
            month: "Febrero",
            utilidad: "275000.00",
            ventas: "925000.00",
            egresos: "280000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "https://www.google.drive/1423nger",
            diot: "https://www.google.drive/1423nger",
          },
          {
            id: 6,
            month: "Marzo",
            year: "2023",
            utilidad: "275000.00",
            ventas: "925000.00",
            egresos: "280000.00",
            isr: "",
            iva: "",
            diot: "https://www.google.drive/1423nge",
          },
        ],
      },
    ],
  },
  {
    id: 24,
    nombre: "Airenlinea SA de CV",
    rfc: "BVA4930245",
    moneda: 'MXN',
    actaConstitutiva: 'https://www.google.drive/1423nger', 
    actaAsamblea: 'https://www.google.drive/1423nger', 
    actaAsambleaExtraordinaria: 'https://www.google.drive/1423nger', 
    poderes: '',
    actasDividendos: '',
    cif: '',
    reports: [
      {
        year: "2024",
        accounting: [
          {
            id: 7,
            month: "Enero",
            year: "2024",
            utilidad: "425000.00",
            ventas: "925000.00",
            egresos: "280000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "https://www.google.drive/1423nger",
            diot: "https://www.google.drive/1423nger",
          },
          {
            id: 8,
            year: "2024",
            month: "Febrero",
            ventas: "925000.00",
            egresos: "280000.00",
            utilidad: "475000.00",
            isr: "https://www.google.drive/1423nger",
            iva: "",
            diot: "",
          },
          {
            id: 9,
            year: "2024",
            month: "Marzo",
            ventas: "925000.00",
            egresos: "280000.00",
            utilidad: "516000.00",
            isr: "",
            iva: "",
            diot: "",
          },
        ],
      },
      {
        year: "2023",
        accounting: [
          {
            id: 10,
            year: "2023",
            month: "Enero",
            ventas: "925000.00",
            egresos: "280000.00",
            utilidad: "186500.00 ",
            isr: "https://www.google.drive/1423nger",
            iva: "https://www.google.drive/1423nger",
            diot: "https://www.google.drive/1423nger",
          },
          { 
            id: 11,
            year: "2023",
            month: "Febrero",
            ventas: "925000.00",
            egresos: "280000.00",
            utilidad: "860000.00 ",
            isr: "https://www.google.drive/1423nger",
            iva: "",
            diot: "",
          },
          { 
            id: 12,
            year: "2023",
            month: "Marzo",
            ventas: "925000.00",
            egresos: "280000.00",
            utilidad: "240000.00",
            isr: "",
            iva: "",
            diot: "",
          },
        ],
      },
    ],
  },
];
