export const nationalities = [
  { label: "Mexicana", value: "Mexicana" },
  { label: "Estadounidense", value: "Estadounidense" },
  { label: "Canadiense", value: "Canadiense" },
  { label: "Brasileña", value: "Brasileña" },
  { label: "Argentina", value: "Argentina" },
  { label: "Colombiana", value: "Colombiana" },
  { label: "Española", value: "Española" },
  { label: "Francesa", value: "Francesa" },
  { label: "Alemana", value: "Alemana" },
  { label: "Italiana", value: "Italiana" },
  { label: "Británica", value: "Británica" },
  { label: "Neerlandesa", value: "Neerlandesa" },
  { label: "Belga", value: "Belga" },
  { label: "Sueca", value: "Sueca" },
  { label: "Suiza", value: "Suiza" },
  { label: "Portuguesa", value: "Portuguesa" },
];
